#!/bin/bash

set -e

hc() {
  herbstclient $*
}

# ===== Theme sttings ================================

active_frame_color='#ff0000'
normal_frame_color='#808080'

hc attr settings.focus_follows_mouse true
hc attr settings.show_frame_decorations if_empty
hc attr settings.frame_normal_opacity 50
hc attr settings.frame_active_opacity 50
hc attr settings.frame_border_width 4
hc attr settings.window_border_active_color $active_frame_color
hc attr settings.window_border_normal_color $normal_frame_color
hc attr settings.frame_border_active_color $active_frame_color
hc attr settings.frame_border_normal_color $normal_frame_color
hc attr settings.window_border_width 4
hc attr settings.window_gap 5
hc attr settings.swap_monitors_to_get_tag true
hc attr settings.default_frame_layout horizontal

# ===== Key binding =================================

Mod=Mod1

hc keyunbind --all

hc keybind $Mod+Control+r      reload
hc keybind $Mod+Control+q      quit

hc keybind $Mod+Return         spawn alacritty
hc keybind $Mod+r              spawn rofi -show drun
hc keybind $Mod+Shift+r        spawn rofi -show run
hc keybind $Mod+c              spawn galculator
hc keybind $Mod+f              set_attr clients.focus.floating toggle
hc keybind $Mod+Tab            cycle_all

hc keybind $Mod+BackSpace      focus_monitor +1
hc keybind $Mod+Delete         close_or_remove

hc keybind $Mod+Left           focus left
hc keybind $Mod+Right          focus right
hc keybind $Mod+Up             focus up
hc keybind $Mod+Down           focus down
  
hc keybind $Mod+Mod4+Left      chain , split left , focus left , spawn alacritty
hc keybind $Mod+Mod4+Right     chain , split right , focus right , spawn alacritty
hc keybind $Mod+Mod4+Up        chain , split top , focus up , spawn alacritty
hc keybind $Mod+Mod4+Down      chain , split bottom , focus down , spawn alacritty

hc keybind $Mod+Shift+Left     shift left
hc keybind $Mod+Shift+Right    shift right
hc keybind $Mod+Shift+Up       shift up
hc keybind $Mod+Shift+Down     shift down

hc keybind $Mod+Control+Left   resize left
hc keybind $Mod+Control+Right  resize right
hc keybind $Mod+Control+Up     resize up
hc keybind $Mod+Control+Down   resize down

for i in {1..9}; do
  hc add $i
  hc keybind $Mod+$i        use_index $((i-1))
  hc keybind $Mod+Shift+$i  chain , move_index $((i-1)) , use_index $((i-1))
done

hc keybind XF86AudioPlay   spawn playerctl play-pause
hc keybind XF86AudioNext   spawn playerctl next
hc keybind XF86AudioPrev   spawn playerctl previous

hc keybind XF86Calculator  spawn rofi -show calc

[ $(hc tag_status | grep -c default) -gt 0 ] && hc use 1 && hc merge_tag default

# ===== Mouse binding =================================

hc mousebind $Mod+Button1 move
hc mousebind $Mod+Button3 resize

# ===== Rules binding =================================

hc unrule --all
hc rule class=Galculator floating=true floatplacement=center focus=on
hc rule class=Signal floating=true floatplacement=center focus=on
hc rule class=vlc floating=true focus=on

hc detect_monitors

